### ISSUE TITLE
`&& echo OK` does not work after `-c urclock`

### ISSUE THREAD

**Issue by mcuee** [avrdudes/avrdude#1192]
Reference:
* https://github.com/avrdudes/avrdude/pull/1171#issuecomment-1325151678

It is strange that `&& echo OK` does not work after `-c urclock`. No pronlems with `-c arduino`.

It is the same under Linux.
```
mcuee@UbuntuSwift3:~/build/avr/avrdude_bin$ ./avrdude -c arduino -P /dev/ttyUSB0 -p m328p
 -U ./Blink.ino.standard.hex -qq && echo OK
OK

mcuee@UbuntuSwift3:~/build/avr/avrdude_bin$ ./avrdude -c urclock -P /dev/ttyUSB0 -p m328p
 -U ./Blink.ino.standard.hex -xbootsize=512 -qq && echo OK

mcuee@UbuntuSwift3:~/build/avr/avrdude_bin$ 
```

**Comment by stefanrueger** [comment]
`-c arduino` pretends chip erase works (but does nothing), so no error is being shown.

`-c urclock` correctly assumes the non-native bootloader won't have CE, so delayes CE to be dealt with by filling the remaining space with 0xff on the next -U flash upload, but marks the shell `exitrc` value provisionally as 1 (error, no echo `OK`) as at this point it does not know whether there will be a correct `-U` flash upload later

The bug is that this then never reset to 0 on successful `-U` to flash.

Will repair

**Comment by mcuee** [comment]
@stefanrueger 
Thanks for the detailed explanation why the issue happened. I can confirm PR #1194 fixed the issue.
