### ISSUE TITLE
Compiler warning with NetBSD build

### ISSUE THREAD

**Issue by mcuee** [avrdudes/avrdude#1460]
There is a warning when building under NetBSD 9.3 (gcc 7.5.0)

![Screenshot 2023-07-01 204224](https://github.com/avrdudes/avrdude/assets/1294740/146e50f7-05c8-4836-b8e9-fe0a36c2e2c1)

**Comment by stefanrueger** [comment]
This is poor compiler analysis, I am afraid.

The queried comparison is of the form `lmax <= lmin+MAX_PAD`, not of the form `(X + c) >= X` by any stretch of imagination as the compiler would have it. It's true that `lmin` and `lmax` are both initialised with the same value in the beginning but later they are computed to be the length of the shortest and longest string in a list:
https://github.com/avrdudes/avrdude/blob/11e8376dfe1ace8ca3235d6e186393f67cd11161/src/term.c#L1205-L1207

The list of strings is from constant read-only tables, the involved string lengths vary, but they are not longer than 100 whilst PAD_MAX is set to be a constant 10. So no danger of overflow either.

The code aligns the terminal `config` output if the shortest and longest strings differ in length by at most 10. The following example proves the queried line of the code runs as intended (in the first example `lmax <= lmin+MAX_PAD` is false, in the second it's true:
```
$ avrdude -qqc dryrun -p m328p -t
avrdude> co rst=
# conf rstdisbl=gpio_pc6_warning_external_reset_disabled # 0
config rstdisbl=external_reset # 1 (factory)
avrdude> co bod=
# conf bodlevel=bod_4v3      # 4
# conf bodlevel=bod_2v7      # 5
# conf bodlevel=bod_1v8      # 6
config bodlevel=bod_disabled # 7 (factory)
```

What happens if you change `int` to `size_t` in line 1183? Might persuade the compiler all is hunky dory.

```
diff --git a/src/term.c b/src/term.c
index 9f88b22d..b707a999 100644
--- a/src/term.c
+++ b/src/term.c
@@ -1180,7 +1180,7 @@ static void printproperty(Cfg_t *cc, int ii, Cfg_opts_t o) {
     vstr = buf;
   }
 
-  int lmin, lmax, llen;
+  size_t lmin, lmax, llen;
   lmin = lmax = strlen(vstr);
 
   if(o.verb > 0) {
```
