### ISSUE TITLE
[bug #55561] FTDI Bitbang not working

### ISSUE THREAD

**Issue by avrs-admin** [avrdudes/avrdude#486]
HannesB <None>
Thu 24 Jan 2019 05:30:26 PM UTC
Programmer hardware: FTDI Bitbang
Device type: ATMega with SPI

I am using AVRDUDE 6.3 on Windows 10.
When i try to program a AVR processor using the FTDI Bitbang methode, windows reports missing FTDI drivers.
All the driver files are present, but to get this working AVRDUDE must be recompiled, with the FTDI Direct D2xx drivers.
I don't have the knowledge how to do this.

As an alternative you can use the normal serial bitbang driver, but this is very slow and, only suitable to program a small program (Bootloader).

I also found an older patched version that will work, but this is not a good solution, because it doesn't support new devices.

This issue was migrated from https://savannah.nongnu.org/bugs/?55561

**Comment by mcuee** [comment]
I think this can be closed as of now since avrdude Windows binary (VS build) is using the custom libftdi which uses D2XX. 
https://github.com/avrdudes/avrdude/wiki/Building-AVRDUDE-for-Windows-using-Visual-Studio
https://github.com/mariusgreuel/avrdude#support-ftdi-devices-via-custom-libftdi

Normal libftdi should also work but one needs to switch the driver from FTDI driver to WinUSB in order to use libftdi.
