### ISSUE TITLE
Port Linux sysfs GPIO feature to libgpiod

### ISSUE THREAD

**Issue by yegorich** [avrdudes/avrdude#831]
According to [libgpiod](https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/about/) description, sysfs interface is deprecated since 4.8. Hence, to enable compatibility with future kernel versions porting to `libgpiod` is required.

**Comment by wutje** [comment]
Note that the linux_spi code already has the GPIO v2 infrastructure implemented.
See init code starting here
https://github.com/avrdudes/avrdude/blob/1c0b70da899628f1cad90e21cba8463a59a4744f/src/linuxspi.c#L176
and actual usage starting here:
https://github.com/avrdudes/avrdude/blob/1c0b70da899628f1cad90e21cba8463a59a4744f/src/linuxspi.c#L110

So instead of a new dependency one could extract this code (init and set GPIO) and reuse it for linux_gpio.

Just my 2 cents.

**Comment by mcuee** [comment]
From here.
* https://github.com/avrdudes/avrdude/pull/917#issuecomment-1179769709

> > Moving to libgpiod may be the ultimate solution. #831
> 
> Absolutely! Now that libgpiod is a part of the linux kernel, it looks like libgpiod is available under /linux/gpio.h, which is how `linuxspi` interacts with the GPIO it uses as reset pin.
> 
> But I have no idea how to port the existing linuxgpio code over to libgpiod. Maybe the person who write linuxgpio in the first place would be interested to look into it?

Hopefully a developer will look into this.

OpenOCD libgpiod codes can be a potential reference. They have both libgpiod and sysfs based codes in the repo.
https://github.com/openocd-org/openocd/blob/master/src/jtag/drivers/linuxgpiod.c
https://github.com/openocd-org/openocd/blob/master/src/jtag/drivers/sysfsgpio.c
